# http-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calendar-http-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: calendar.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calendar
                port:
                  number: 80
---
# grpc-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calendar-grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: grpc.calendar.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calendar
                port:
                  number: 50051