apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-rabbitmq
  template:
    metadata:
      labels:
        app: calendar-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management
          ports:
            - containerPort: 5672   # AMQP
            - containerPort: 15672  # Management UI
          envFrom:
            - configMapRef:
                name: calendar-env
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-rabbitmq
spec:
  selector:
    app: calendar-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP
