x-ldflags: &ldflags
  args:
    LDFLAGS: "${LDFLAGS}"

services:
  postgres:
    image: postgres:15
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - calendar_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ${RABBITMQ_HOST}
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - calendar_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: build/Dockerfile.migrations
    container_name: calendar_migrations
    image: calendar_migrations:${RELEASE}
    env_file: .env
    networks:
      - calendar_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  calendar:
    build:
      context: .
      dockerfile: build/Dockerfile.calendar
      <<: *ldflags
    container_name: ${CALENDAR_HOST}
    image: ${CALENDAR_HOST}:${RELEASE}
    env_file:
      - .env
    ports:
      - "${CALENDAR_PORT}:8080"
      - "${CALENDAR_GRPC_PORT}:50051"
    networks:
      - calendar_network
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  scheduler:
    build:
      context: .
      dockerfile: build/Dockerfile.scheduler
      <<: *ldflags
    container_name: ${CALENDAR_SCHEDULER_HOST}
    image: ${CALENDAR_SCHEDULER_HOST}:${RELEASE}
    env_file:
      - .env
    networks:
      - calendar_network
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f /opt/calendar/calendar-scheduler || exit 1" ]
      interval: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  sender:
    build:
      context: .
      dockerfile: build/Dockerfile.sender
      <<: *ldflags
    container_name: ${CALENDAR_SENDER_HOST}
    image: ${CALENDAR_SENDER_HOST}:${RELEASE}
    env_file:
      - .env
    networks:
      - calendar_network
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f /opt/calendar/calendar-sender || exit 1" ]
      interval: 5s
      retries: 3
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  calendar_network:
    driver: bridge
