logger:
 level: "INFO"
 type: "json" # or text

server:
  host: "0.0.0.0"
  port: 8080

storage:
#  type: "memory" # or "sql"
  type: "sql"
  dsn: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable'
